name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev portaudio19-dev

      - name: Build
        run: go build -v ./...
