name: React

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gui
      CI: ""
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install
        working-directory: ${{env.working-directory}}

      - name: Build Site
        run: yarn build
        working-directory: ${{env.working-directory}}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            gui/dist
